import Head from 'next/head'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import Main from '../components/Main'

export default function Sobre() {
  return (
    <>
      <Head>
        <title>Agro Sena|</title>
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <Footer />
    </>
  )
}
